name: Generate Snake Animation

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  # Permite execução manual na aba Actions
  workflow_dispatch:
  # Executa a cada push na branch main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1. Faz o checkout do repositório
      - uses: actions/checkout@v4

      # 2. Gera o SVG da cobrinha
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: v1niic
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Envia os arquivos gerados para a branch "output"
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
